language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
install: true
sudo: required
services:
  - docker
before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
script:
  - npm install --ignore-scripts
  - docker exec -it emscripten make
  - make lint
  - npm run test:js
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.npm
after_success: npm run test:cov

jobs:
  include:
    - stage: Deploy website
      language: node_js
      node_js: "9"
      install: true
      script:
        - git config --global user.email "${GH_EMAIL}"
        - git config --global user.name "${GH_NAME}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && npm install && GIT_USER="${GH_NAME}" npm run publish-gh-pages
      branches:
        only:
          - master
      if: tag =~ ^\d+\.\d+\.\d+
      after_success: echo "Website online"